CREATE DATABASE CINEMINHA;

CREATE TABLE USUARIOS(
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    PLANO VARCHAR(50) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    CIDADE VARCHAR(255) NOT NULL,
    ESTADO VARCHAR(255) NOT NULL,
    ENDERECO VARCHAR(255) NOT NULL
);

CREATE TABLE FILMES(
    ID_FILME INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    ANO_LANCAMENTO DATE,
    SINOPSE TEXT,
    CAMINHO_POSTER VARCHAR(255)
);

CREATE TABLE GENEROS (
    ID_GENERO INT AUTO_INCREMENT PRIMARY KEY,
    DS_NOME VARCHAR(255) NOT NULL UNIQUE    
);

CREATE TABLE ATORES(
    ID_ATOR INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    ANIVERSARIO DATE
);

CREATE TABLE FILME_GENERO(
    ID_FILME INT,
    ID_GENERO INT,
    PRIMARY KEY (ID_FILME, ID_GENERO),
    FOREIGN KEY (ID_FILME) REFERENCES FILMES(ID_FILME),
    FOREIGN KEY (ID_GENERO) REFERENCES GENEROS(ID_GENERO)
);

CREATE TABLE FILME_ATOR(
    ID_FILME INT,
    ID_ATOR INT,
    PRIMARY KEY (ID_FILME, ID_ATOR),
    FOREIGN KEY (ID_FILME) REFERENCES FILMES(ID_FILME),
    FOREIGN KEY (ID_ATOR) REFERENCES ATORES(ID_ATOR)
);

CREATE TABLE STATUS_CONTROLE_ROTINA(
    ID_STATUS INT AUTO_INCREMENT PRIMARY KEY,
    DS_STATUS VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS CONTROLE_ROTINA (
    ID_CONTROLE_ROTINA INT AUTO_INCREMENT PRIMARY KEY,
    ID_STATUS_ROTINA INT,
    ULTIMA_ATUALIZACAO DATETIME,
    MENSAGEM TEXT,
    FOREIGN KEY (ID_STATUS_ROTINA) REFERENCES STATUS_CONTROLE_ROTINA(ID_STATUS)
);

CREATE TABLE FAVORITOS (
    ID_USUARIO INT,
    ID_FILME INT,
    PRIMARY KEY (ID_USUARIO, ID_FILME),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
    FOREIGN KEY (ID_FILME) REFERENCES FILMES(ID_FILME)
);


CREATE TABLE AVALIACOES (
    ID_AVALIACAO INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT,
    ID_FILME INT,
    NOTA INT CHECK (NOTA BETWEEN 1 AND 10),
    COMENTARIO TEXT,
    DATA_AVALIACAO DATETIME,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
    FOREIGN KEY (ID_FILME) REFERENCES FILMES(ID_FILME)
);

CREATE TABLE COMENTARIOS (
    ID_COMENTARIO INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT,
    ID_FILME INT,
    COMENTARIO TEXT,
    DATA_COMENTARIO DATETIME,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
    FOREIGN KEY (ID_FILME) REFERENCES FILMES(ID_FILME)
);
