INSERT INTO STATUS_CONTROLE_ROTINA (DS_STATUS) VALUES ('Executado com sucesso');
INSERT INTO STATUS_CONTROLE_ROTINA (DS_STATUS) VALUES ('Falha no processo');
INSERT INTO STATUS_CONTROLE_ROTINA (DS_STATUS) VALUES ('Pendente');



